services:
  postgres:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading
    ports:
      - 5432:5432
    volumes:
       - pgdata:/var/lib/postgresql/data
       - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U trading"]
      interval: 5s
      timeout: 5s
      retries: 5
  news_agent:
    build: .
    env_file: .env
    environment:
      DATABASE_URL: postgresql://trading:postgres@postgres:5432/trading
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
volumes:
  pgdata: null
 